# Generated by Django 3.0.2 on 2020-03-26 13:46

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseoperation',
            name='operators',
            field=models.CharField(choices=[('+', _operator.add), ('-', _operator.sub), ('*', _operator.mul), ('/', _operator.truediv)], default='+', max_length=4),
        ),
    ]
