# Generated by Django 3.0.2 on 2020-03-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='idUser',
        ),
    ]
