# Generated by Django 3.0.2 on 2020-03-26 14:31

import _operator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0002_auto_20200326_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseoperation',
            name='operators',
            field=models.CharField(choices=[('+', _operator.add), ('-', _operator.sub), ('/', _operator.mul), ('*', _operator.truediv)], default='+', max_length=4),
        ),
    ]
