# Generated by Django 3.0.2 on 2020-03-15 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0002_auto_20200315_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='idUser',
            new_name='user',
        ),
    ]
