# Generated by Django 3.0.2 on 2020-02-27 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0002_exercise_exercisedone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseDone',
        ),
    ]
