# Generated by Django 3.0.2 on 2020-03-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0003_auto_20200326_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseoperation',
            name='operators',
            field=models.CharField(choices=[('+', 'addition'), ('-', 'soustraction'), ('/', 'division'), ('*', 'multiplication')], default='+', max_length=4),
        ),
    ]
