# Generated by Django 3.0.2 on 2020-02-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0004_auto_20200227_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='relation',
        ),
        migrations.AddField(
            model_name='exercise',
            name='relationExerciseRequirement',
            field=models.ManyToManyField(related_name='related_to_exerciserequirement', through='mathematorApp.ExerciseRequirement', to='mathematorApp.Exercise'),
        ),
        migrations.CreateModel(
            name='ExerciseDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbWrong', models.IntegerField()),
                ('nbRight', models.IntegerField()),
                ('idExercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematorApp.Exercise')),
                ('idStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathematorApp.Student')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='relationExerciseDone',
            field=models.ManyToManyField(related_name='related_to_exercisedone', through='mathematorApp.ExerciseDone', to='mathematorApp.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='relationExerciseDone',
            field=models.ManyToManyField(related_name='related_to_exercisedone', through='mathematorApp.ExerciseDone', to='mathematorApp.Exercise'),
        ),
    ]
