# Generated by Django 3.0.2 on 2020-03-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0004_auto_20200326_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisefix',
            name='result',
            field=models.FloatField(),
        ),
    ]
