# Generated by Django 3.0.2 on 2020-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0005_auto_20200327_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseoperation',
            name='operators',
            field=models.CharField(blank=True, choices=[('+', 'addition'), ('-', 'soustraction'), ('/', 'division'), ('*', 'multiplication')], default='+', max_length=4),
        ),
    ]
