# Generated by Django 3.0.2 on 2020-03-01 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0005_auto_20200227_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseSimpleOperation',
            fields=[
                ('exercise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mathematorApp.Exercise')),
                ('rangeMin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rangeMax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rangeStep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nbOperation', models.IntegerField()),
                ('operators', models.CharField(choices=[('+', 'addition'), ('-', 'soustraction'), ('/', 'division'), ('*', 'multiplication')], default='+', max_length=1)),
            ],
            bases=('mathematorApp.exercise',),
        ),
        migrations.AddField(
            model_name='exercise',
            name='donnee',
            field=models.CharField(default='', max_length=50),
        ),
    ]
