# Generated by Django 3.0.2 on 2020-03-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0005_auto_20200319_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExerciseOperations',
            new_name='ExerciseOperation',
        ),
    ]
