# Generated by Django 3.0.2 on 2020-03-27 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0006_auto_20200327_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseoperation',
            name='operators',
            field=models.CharField(choices=[('+', 'addition'), ('-', 'soustraction'), ('/', 'division'), ('*', 'multiplication')], default='+', max_length=4, validators=[django.core.validators.RegexValidator('^[\\+\\*\\/\\-]*$')]),
        ),
    ]
