# Generated by Django 3.0.2 on 2020-03-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathematorApp', '0007_exercisefixdonneeresultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesimpleoperation',
            name='operators',
            field=models.CharField(choices=[('+', 'addition'), ('-', 'soustraction'), ('/', 'division'), ('*', 'multiplication')], default='+', max_length=4),
        ),
    ]
